pipeline {
  agent any

  environment {
    DOCKERHUB_USER = "amandevop"
    BACKEND_IMAGE  = "ecommerce-backend"
    FRONTEND_IMAGE = "ecommerce-frontend"
  }

  stages {

    stage("Checkout Code") {
      steps {
        checkout scm
      }
    }

    stage("Get Git Commit Hash") {
      steps {
        script {
          env.GIT_SHA = sh(
            script: "git rev-parse --short HEAD",
            returnStdout: true
          ).trim()
        }
        echo "Using image tag: ${GIT_SHA}"
      }
    }

    stage("Docker Login") {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker_creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          '''
        }
      }
    }

    stage("Build & Push Images") {
      steps {
        sh """
          docker build -t $DOCKERHUB_USER/$BACKEND_IMAGE:$GIT_SHA ./e-commerce-website/backend
          docker build -t $DOCKERHUB_USER/$FRONTEND_IMAGE:$GIT_SHA ./e-commerce-website/frondend

          docker push $DOCKERHUB_USER/$BACKEND_IMAGE:$GIT_SHA
          docker push $DOCKERHUB_USER/$FRONTEND_IMAGE:$GIT_SHA
        """
      }
    }

    stage("Update Kubernetes Manifests") {
      steps {
        sh """
          sed -i 's|image: amandevop/ecommerce-backend:.*|image: amandevop/ecommerce-backend:$GIT_SHA|' k8s/backend/deployment.yaml
          sed -i 's|image: amandevop/ecommerce-frontend:.*|image: amandevop/ecommerce-frontend:$GIT_SHA|' k8s/frontend/deployment.yaml
        """
      }
    }

    stage("Commit & Push Manifests") {
      steps {
        sh """
          git config user.email "jenkins@ci.com"
          git config user.name "jenkins"

          git add k8s/backend/deployment.yaml k8s/frontend/deployment.yaml
          git commit -m "Deploy images $GIT_SHA"
          git push origin master
        """
      }
    }
  }
}
