pipeline {
  agent any

  environment {
    DOCKERHUB_USER = "amandevop"
    BACKEND_IMAGE  = "ecommerce-backend"
    FRONTEND_IMAGE = "ecommerce-frontend"
  }

  stages {

    stage("Checkout Code") {
      steps {
        checkout scm
      }
    }

    stage("Get Git Commit Hash") {
      steps {
        script {
          env.GIT_SHA = sh(
            script: "git rev-parse --short HEAD",
            returnStdout: true
          ).trim()
        }
        echo "Using image tag: ${GIT_SHA}"
      }
    }

    stage("Docker Hub Login") {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker_creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo \$DOCKER_PASS | docker login \
              -u \$DOCKER_USER \
              --password-stdin
          """
        }
      }
    }

    stage("Build Backend Image") {
      steps {
        sh """
          docker build \
            -t \$DOCKERHUB_USER/\$BACKEND_IMAGE:\$GIT_SHA \
            ./e-commerce-website/backend
        """
      }
    }

    stage("Build Frontend Image") {
      steps {
        sh """
          docker build \
            -t \$DOCKERHUB_USER/\$FRONTEND_IMAGE:\$GIT_SHA \
            ./e-commerce-website/frondend
        """
      }
    }

    stage("Push Images to Docker Hub") {
      steps {
        sh """
          docker push \$DOCKERHUB_USER/\$BACKEND_IMAGE:\$GIT_SHA
          docker push \$DOCKERHUB_USER/\$FRONTEND_IMAGE:\$GIT_SHA
        """
      }
    }
  }
}